apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exporter-service-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: exporter-app
  endpoints:
  - port: exporter
