apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: {{.Values.proxy}}
        backend:
          serviceName: haproxy-app
          servicePort: 80
      - path: {{.Values.stat}}
        backend:
          serviceName: haproxy-app
          servicePort: 9000
